// Tên các màn hình có trong App
export enum routeNames {
HOMESCREEN = "HOMESCREEN",
DETAILSSCREEN = "DETAILSSCREEN",

  // Khối màn EKEY
  SCREEN_UPLOAD_OTHER_DOC = 'SCREEN_UPLOAD_OTHER_DOC',


  // Khối màn vay khi sở hữu ô tô
  SCREEN_LOAN_PROPOSAL_BY_OTO = 'SCREEN_LOAN_PROPOSAL_BY_OTO',

  SCREEN_SUCCESS = 'SCREEN_SUCCESS',

  // Khối màn vay khi sở hữu giấy phép kinh doanh
  SCREEN_LOAN_PROPOSAL_BY_BUSINESS_LICENSE = 'SCREEN_LOAN_PROPOSAL_BY_BUSINESS_LICENSE',

  // Khối màn rút tiền lần đầu khi hạn mức vay chưa có
  SCREEN_SELECT_OPTION_LOAN = 'SCREEN_SELECT_OPTION_LOAN',

  //Khối màn xác nhận đề xuất
  SCREEN_CONFIRM_PROPOSAL = 'SCREEN_CONFIRM_PROPOSAL',

  // Màn chứng từ thu nhập
  SCREEN_UPLOAD_INCOME_CERTIFICATE = 'SCREEN_UPLOAD_INCOME_CERTIFICATE',
  SCREEN_CAPITAL_USE_PLAN = 'SCREEN_CAPITAL_USE_PLAN',
  SCREEN_MERRY_STATUS = 'SCREEN_MERRY_STATUS',
}
